#!/bin/sh
## compile ##
clear                                                                   \
 && [[ -d bin ]] || mkdir bin                                           \
 && g++ -std=c++11 -I./src -c ./src/customer.cpp    -o ./bin/customer.o \
 && g++ -std=c++11 -I./src -c ./src/order.cpp       -o ./bin/order.o    \
 && g++ -std=c++11 -I./src -c ./src/ordering.cpp    -o ./bin/ordering.o \
 && g++ bin/order.o bin/customer.o bin/ordering.o   -o bin/ordering     \
 && rm  bin/order.o bin/customer.o bin/ordering.o                       \
 && echo "Success! Program can be found in the 'bin' directory" || echo "Error: Compiler Failed... "