#!/bin/sh
## compile ##
clear                                                                       \
 && [[ -d bin ]] || mkdir bin                                               \
 && g++ -std=c++11 -I./src -c ./src/fileIO.cpp        -o ./bin/fileIO.o     \
 && g++ -std=c++11 -I./src -c ./src/ordering.cpp      -o ./bin/ordering.o   \
 && g++ bin/fileIO.o bin/ordering.o    -o bin/ordering                      \
 && rm  bin/fileIO.o bin/ordering.o                                         \
 && echo "Success" || echo "Error: Compiler Failed..."